import { useState } from "react"
import { useNavigate } from "react-router-dom"
import { ArrowRight, Check, MapPin, UserRound } from "lucide-react"
import { updateUserContext } from "@/lib/context"

export default function Context() {
 const navigate=useNavigate();const[state,setState]=useState("");const[roleCategory,setRoleCategory]=useState("");const[vulnerabilityTags,setVulnerabilityTags]=useState<string[]>([]);const[error,setError]=useState("");const[isLoading,setIsLoading]=useState(false)
 const toggle=(tag:string)=>{setError("");setVulnerabilityTags(c=>c.includes(tag)?c.filter(x=>x!==tag):[...c,tag])}
 const save=async()=>{if(isLoading)return;setError("");setIsLoading(true);try{const r=await updateUserContext({state:state||undefined,roleCategory:roleCategory||undefined,vulnerabilityTags:vulnerabilityTags.length?vulnerabilityTags:undefined});if(!r.success||!r.data?.saved){setError(r.error?.message??"Unable to save your context. Please try again.");return}navigate("/incident")}catch{setError("Unable to connect to the server. Please try again.")}finally{setIsLoading(false)}}
 return <div className="flow-page"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="flow-wrap"><div className="flow-progress"><span className="done">01</span><i/><span className="current">02</span><i/><span>03</span></div><div className="flow-heading"><div className="flow-kicker">STEP 2 OF 3</div><h1>A little about you.</h1><p>This optional context can help HAQSETU make your guidance more relevant. Skip anything you don't want to share.</p></div>
  <div className="flow-card"><div className="field-grid"><label className="field"><span><MapPin size={14}/> State</span><select value={state} onChange={e=>{setState(e.target.value);setError("")}}><option value="">Select your state</option><option>Maharashtra</option><option>Delhi</option><option>Karnataka</option><option>Gujarat</option><option>Uttar Pradesh</option><option>Other</option></select></label><label className="field"><span><UserRound size={14}/> What best describes you?</span><select value={roleCategory} onChange={e=>{setRoleCategory(e.target.value);setError("")}}><option value="">Select your role</option><option value="worker">Worker</option><option value="student">Student</option><option value="tenant">Tenant</option><option value="employer">Employer</option><option value="other">Other</option></select></label></div>
   <div className="tag-section"><strong>Anything that may be relevant?</strong><p>Select all that apply. This is optional.</p><div className="tag-list">{[["gig_worker","Gig worker"],["migrant_worker","Migrant worker"],["person_with_disability","Person with disability"],["senior_citizen","Senior citizen"]].map(([v,l])=>{const s=vulnerabilityTags.includes(v);return <button type="button" key={v} className={`tag ${s?"selected":""}`} onClick={()=>toggle(v)}><Check size={13}/>{l}</button>})}</div></div>
   {error&&<div className="form-error">{error}</div>}<div className="flow-actions"><button className="primary-btn" onClick={save} disabled={isLoading}>{isLoading?"Saving...":"Continue"}<ArrowRight size={16}/></button><button className="secondary-btn" onClick={()=>navigate("/incident")} disabled={isLoading}>Skip for now</button></div>
  </div></div></div>
}
