import { useRef, useState, type FormEvent } from "react"
import { useNavigate } from "react-router-dom"
import { ArrowUp, Mic, MicOff, PenLine, ShieldCheck } from "lucide-react"
import { createIncident } from "@/lib/incidents"

type InputMode="text"|"voice"
export default function Incident(){
 const navigate=useNavigate();const[language,setLanguage]=useState<"en"|"hi">("en");const[inputMode,setInputMode]=useState<InputMode>("text");const[incidentText,setIncidentText]=useState("");const[audioBase64,setAudioBase64]=useState<string|null>(null);const[isRecording,setIsRecording]=useState(false);const[isSubmitting,setIsSubmitting]=useState(false);const[error,setError]=useState("");const mediaRecorderRef=useRef<MediaRecorder|null>(null);const audioChunksRef=useRef<Blob[]>([])
 const start=async()=>{setError("");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunksRef.current=[];const rec=new MediaRecorder(stream,{mimeType:"audio/webm;codecs=opus"});mediaRecorderRef.current=rec;rec.ondataavailable=e=>{if(e.data.size)audioChunksRef.current.push(e.data)};rec.onstop=()=>{const blob=new Blob(audioChunksRef.current,{type:rec.mimeType});const reader=new FileReader();reader.onloadend=()=>{const r=reader.result;if(typeof r==="string")setAudioBase64(r.split(",")[1]??null)};reader.readAsDataURL(blob);stream.getTracks().forEach(t=>t.stop())};rec.start();setIsRecording(true)}catch{setError("Microphone access was denied or is not available.")}}
 const stop=()=>{const r=mediaRecorderRef.current;if(r&&r.state!=="inactive"){r.stop();setIsRecording(false)}}
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(inputMode==="text"&&!incidentText.trim()){setError("Please describe what happened.");return}if(inputMode==="voice"&&!audioBase64){setError("Please record your situation before submitting.");return}setIsSubmitting(true);try{const r=await createIncident({inputMode,language,text:inputMode==="text"?incidentText.trim():null,audioBase64:inputMode==="voice"?audioBase64:null});if(!r.success||!r.data){setError(r.error?.message??"We couldn't process your request. Please try again.");return}if("emptyTranscription"in r.data&&r.data.emptyTranscription){setError("We could not detect clear speech in your recording. Please try again or use text input.");return}if(!r.data.incidentId){setError("We couldn't create the incident. Please try again.");return}navigate(`/result/${r.data.incidentId}`)}catch{setError("We couldn't connect to the service. Please try again.")}finally{setIsSubmitting(false)}}
 if(isSubmitting)return <div className="flow-page"><div className="loading-card"><div className="loading-mark">H</div><h1>Understanding your situation</h1><p>Please wait while HAQSETU processes what you shared.</p><div className="loading-bar"><span/></div></div></div>
 return <div className="assistant-page"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><header className="assistant-topbar"><div className="haq-brand"><span className="brand-mark">H</span><span>HAQSETU</span></div><div className="assistant-status"><span className="status-dot"/> Ready to help</div></header><main className="assistant-workspace">
  <aside className="assistant-sidebar"><div className="profile-mini"><div className="profile-avatar">H</div><div><strong>HAQSETU</strong><span>Know Your Rights</span></div></div><nav><button className="active"><span>⌂</span> Assistant</button><button onClick={()=>navigate("/incident")}><span>↻</span> New query</button></nav><div className="sidebar-note"><ShieldCheck size={17}/><div><strong>Legal awareness</strong><small>General information, not legal advice.</small></div></div></aside>
  <section className="incident-panel"><div className="incident-header"><div><div className="section-label">YOUR PRIVATE WORKSPACE</div><h1>Tell us what happened.</h1><p>Describe the situation in your own words. We'll help you understand what may be happening and what you can do next.</p></div><div className="header-badge"><span className="status-dot"/> Know Your Rights</div></div>
   <form onSubmit={submit} className="incident-form"><div className="option-row"><div><span className="option-label">Preferred language</span><p>Choose how you'd like the guidance presented.</p></div><div className="segmented"><button type="button" className={language==="en"?"selected":""} onClick={()=>setLanguage("en")}>English</button><button type="button" className={language==="hi"?"selected":""} onClick={()=>setLanguage("hi")}>हिंदी</button></div></div>
    <div className="option-row"><div><span className="option-label">How would you like to describe it?</span><p>Write the situation or record a short voice note.</p></div><div className="segmented"><button type="button" className={inputMode==="text"?"selected":""} onClick={()=>{setInputMode("text");setAudioBase64(null)}}><PenLine size={14}/> Write</button><button type="button" className={inputMode==="voice"?"selected":""} onClick={()=>{setInputMode("voice");setIncidentText("")}}><Mic size={14}/> Voice</button></div></div>
    {inputMode==="text"?<div className="composer-block"><label htmlFor="incident">What happened?</label><div className="large-composer"><textarea id="incident" rows={7} maxLength={2000} placeholder="Start with what happened, who was involved, and what you're concerned about..." value={incidentText} onChange={e=>{setIncidentText(e.target.value);setError("")}}/><span>{incidentText.length}/2000</span></div></div>:<div className="voice-card"><div className="voice-icon">{isRecording?<MicOff size={24}/>:<Mic size={24}/>}</div><h3>{isRecording?"Recording your situation...":"Record your situation"}</h3><p>Speak clearly and describe what happened.</p>{!isRecording?<button type="button" className="primary-btn" onClick={start}><Mic size={16}/> Start recording</button>:<button type="button" className="recording-btn" onClick={stop}><MicOff size={16}/> Stop recording</button>}{!isRecording&&audioBase64&&<span className="ready-note">✓ Recording ready</span>}</div>}
    {error&&<div className="form-error">{error}</div>}<div className="incident-submit-row"><div><strong>Ready when you are.</strong><span>Your information is used to provide legal-awareness guidance.</span></div><button className="primary-btn" type="submit" disabled={isRecording}><ArrowUp size={17}/> Get guidance</button></div>
   </form></section>
 </main></div>
}
