import { useState, type FormEvent } from "react"
import { useNavigate } from "react-router-dom"
import { ArrowLeft, ArrowRight, CheckCircle2, LockKeyhole, Smartphone } from "lucide-react"
import { requestOtp, verifyOtp } from "@/lib/auth"

export default function Login() {
 const navigate=useNavigate(); const [phoneNumber,setPhoneNumber]=useState(""); const [otp,setOtp]=useState(""); const [otpSent,setOtpSent]=useState(false); const [error,setError]=useState(""); const [isLoading,setIsLoading]=useState(false)
 const send=async(e:FormEvent)=>{e.preventDefault();setError("");const d=phoneNumber.replace(/\D/g,"");if(d.length!==10){setError("Please enter a valid 10-digit mobile number.");return}setIsLoading(true);try{const r=await requestOtp(`+91${d}`);if(!r.success||!r.data?.otpSent){setError(r.error?.message??"Unable to send OTP. Please try again.");return}setOtpSent(true)}catch{setError("Unable to connect to the server. Please try again.")}finally{setIsLoading(false)}}
 const verify=async(e:FormEvent)=>{e.preventDefault();setError("");if(otp.length!==6){setError("Please enter the 6-digit OTP.");return}setIsLoading(true);try{const d=phoneNumber.replace(/\D/g,"");const r=await verifyOtp(`+91${d}`,otp);if(!r.success||!r.data){setError(r.error?.message??"Invalid OTP. Please try again.");return}localStorage.setItem("ps25_token",r.data.token);localStorage.setItem("userId",r.data.userId);navigate("/context")}catch{setError("Unable to connect to the server. Please try again.")}finally{setIsLoading(false)}}
 return <div className="auth-page"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><button className="auth-back" onClick={()=>navigate("/")}><ArrowLeft size={16}/> Back to HAQSETU</button>
  <div className="auth-layout"><div className="auth-copy"><div className="eyebrow"><span className="pulse"/> Secure access</div><h1>Start with a clearer understanding of your rights.</h1><p>Sign in with your mobile number to continue to your private HAQSETU guidance workspace.</p><div className="auth-points"><span><CheckCircle2 size={16}/> Simple, structured guidance</span><span><CheckCircle2 size={16}/> Evidence and next-step support</span><span><CheckCircle2 size={16}/> Official resources when available</span></div></div>
   <div className="auth-card"><div className="auth-logo">H</div>{!otpSent?<><div className="auth-title">Welcome to HAQSETU</div><p className="auth-sub">Enter your mobile number to securely continue.</p><form onSubmit={send} className="auth-form"><label htmlFor="phone">Mobile number</label><div className="phone-field"><span>+91</span><input id="phone" type="tel" inputMode="numeric" maxLength={10} placeholder="10-digit number" value={phoneNumber} onChange={e=>{setPhoneNumber(e.target.value.replace(/\D/g,""));setError("")}}/></div>{error&&<div className="form-error">{error}</div>}<button className="primary-btn auth-submit" disabled={isLoading}><Smartphone size={16}/>{isLoading?"Sending OTP...":"Send OTP"}<ArrowRight size={16}/></button></form></>:<><div className="auth-title">Verify your number</div><p className="auth-sub">Enter the 6-digit OTP sent to <strong>+91 {phoneNumber}</strong>.</p><form onSubmit={verify} className="auth-form"><label htmlFor="otp">Verification code</label><input className="otp-input" id="otp" type="text" inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="000000" value={otp} onChange={e=>{setOtp(e.target.value.replace(/\D/g,""));setError("")}}/>{error&&<div className="form-error">{error}</div>}<button className="primary-btn auth-submit" disabled={isLoading}><LockKeyhole size={16}/>{isLoading?"Verifying...":"Verify OTP"}<ArrowRight size={16}/></button><button type="button" className="text-btn" onClick={()=>{setOtpSent(false);setOtp("");setError("")}}>Change mobile number</button></form></>}<p className="auth-disclaimer">HAQSETU provides general legal awareness, not legal advice.</p></div>
  </div></div>
}
